create type taxation_type as enum ('GENERAL', 'WINNING');
create type taxation_method as enum ('AMOUNT', 'RATE');

create table if not exists trader
(
    id                      bigint generated by default as identity primary key,
    trader_id               bigint,
    taxation_type           taxation_type,
    taxation_method         taxation_method,
    taxation_amount         decimal,
    taxation_rate           decimal
);

ALTER TABLE trader
    ADD CONSTRAINT unique_trader_id UNIQUE (trader_id);

CREATE INDEX trader_id_idx
    ON trader (trader_id);

ALTER TABLE trader
    ADD CONSTRAINT check_taxation_fields
        CHECK (
            (taxation_method = 'AMOUNT' AND taxation_amount IS NOT NULL AND taxation_amount > 0) OR
            (taxation_method = 'RATE' AND taxation_rate IS NOT NULL AND taxation_rate > 0)
            );