
create table if not exists match_event
(
    id              bigint generated by default as identity
        primary key,
    match_id        varchar,
    market_id       bigint,
    outcome_id      varchar,
    specifiers      varchar,
    sequence_number bigint,
    processing_time bigint,
    timestamp       timestamp default current_timestamp
);

